[common] I1926 systemd images common (#6672)
* make the example role testable

add documentation on what the example role does
test for systemd

* add the example role tests on GA

* switch common role to using new image

* the GA container is slower to boot systemd

this leads to a race condition, we make it run up to 10 times with a 3s
delay.

* we check for systemd runtime

assert the process id one is systemd-like

* this is an example

* be specific about what is tested

* wait for systemd to initialize

* force architecture

* reduce cgroup overhead

* reduce the wait from infinite to 60 seconds

* provide best effort for systemd

* make the image selection explicit

* make local environment variables

* molecule documentation

* remove the belts and suspenders for common

* pull the image earlier than the tests

* retry when the runner network is flaky

* add debug on failure

the docker image already has /sbin/init remove it from molecule

diff --git a/.github/workflows/molecule_tests.yml b/.github/workflows/molecule_tests.yml
--- a/.github/workflows/molecule_tests.yml
+++ b/.github/workflows/molecule_tests.yml
@@ -22,7 +22,7 @@ jobs:
           - dpul
           # - dss
           # - elixir
-          # - ealapps
+          - example
           - extra_path
           - ezproxy
           - ffmpeg
@@ -89,21 +89,46 @@ jobs:
           git config --global http.postBuffer 1048576000
           for i in 1 2 3 4 5; do git clone https://github.com/pulibrary/princeton_ansible.git . && break || sleep 15; done
           git checkout ${{ github.sha }}
+
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: "3.11"
+
       - name: cache python environment
         uses: actions/cache@v3
         with:
           path: ${{ env.pythonLocation }}
           key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
           #- name: Setup upterm session
           #uses: lhotari/action-upterm@v1
+          #
+      - name: Enable Docker retry for GHCR pulls
+        run: |
+          # bump Docker's default timeouts & retries
+          echo '{ "registry-mirrors": [], "debug": true }' | sudo tee /etc/docker/daemon.json
+          sudo systemctl restart docker
+
+      # pull the image early
+      - name: Pre-pull Molecule base image
+        run: |
+          docker pull ghcr.io/pulibrary/vm-builds/ubuntu-22.04:latest
+
       - name: Run tests
+        timeout-minutes: 15
+        env:
+          MOLECULE_DOCKER_PLATFORM: linux/amd64
         run: |
           ROLE=${{ matrix.role }} python run_molecule.py
+
+      - name: Debug on failure
+        if: failure()
+        run: |
+          docker ps -a
+          docker logs $(docker ps -aq --filter name=instance) || true
+
